.travis.yml

| Is bugfix?    | yes
| New feature?  | no
| Breaks BC?    | no
| Tests pass?   | yes
| Fixed issues  | no

Test coverage fix

---

src/StringHelper.php
tests/StringHelperTest.php

| New feature?  | ✔️
| Breaks BC?    | ✔️
| Tests pass?   | ✔️
| Fixed issues  | #16

StringHelper::truncate with default horizontal ellipsis #16

---

tests/InflectorTest.php

| Tests pass?   | ✔️
| Fixed issues  | #22

Inflector::slug() with empty replacement

---

.github/workflows/build.yml
.github/workflows/mutation.yml
.github/workflows/static.yml
composer.json
tests/IsOneOfAssert.php

Remove circular dependency

---

src/Inflector.php
tests/InflectorTest.php

| Fixed issues  | Add inflector tests

Add inflector tests

---

src/StringHelper.php
tests/StringHelperTest.php

| Fixed issues  | Add string helper tests

Add string helper tests

---

src/Inflector.php
src/StringHelper.php
tests/InflectorTest.php
tests/IsOneOfAssert.php
tests/StringHelperTest.php

Initial cleanup

---

src/Inflector.php
src/StringHelper.php
tests/InflectorTest.php
tests/StringHelperTest.php

Adjustments

---

psalm.xml
src/Inflector.php
src/NumericHelper.php
src/StringHelper.php
tests/NumericHelperTest.php
tests/StringHelperTest.php
tests/WildcardPatternTest.php

Psalm improvements

---

.github/workflows/bc.yml_
.github/workflows/build.yml
.github/workflows/mutation.yml
.github/workflows/static.yml
README.md

Fix minor corrections.

---

CHANGELOG.md
README.md
src/NumericHelper.php
tests/NumericHelperTest.php

Add method NumericHelper::isInteger

---

README.md
composer.json
src/StringHelper.php

Adopt psalm, improve readme and update dev dependencies

---

composer.json

Improve composer description

---

.editorconfig
.github/workflows/bc.yml
.github/workflows/build.yml
.github/workflows/mutation.yml
.github/workflows/static.yml
psalm.xml
src/StringHelper.php
src/WildcardPattern.php

Fix psalm errors + Improve GitHub actions

---

CHANGELOG.md
README.md
src/StringHelper.php
tests/InflectorTest.php
tests/StringHelperTest.php

Add `StringHelper::parsePath()`

---

CHANGELOG.md
src/StringHelper.php

Improve `StringHelper::parsePath()` method annotation

---

.styleci.yml
CHANGELOG.md
README.md
src/CombinedRegexp.php
tests/CombinedRegexpTest.php

Combined regexp

---

CHANGELOG.md
src/Inflector.php
tests/InflectorTest.php

Add `$strict` parameter to `StringHelper::toSnakeCase() method

---

.editorconfig
README.md

Minor improve readme and .editorconfig

---

CHANGELOG.md
src/WildcardPattern.php

Increase Wildcard Pattern speed
